### ISSUE TITLE
Validate the map

### ISSUE THREAD

**Issue by JeganMurugan01** [VIJAYGOKULRAJ/project-api#5]
`  {column.map((colItem) => {` 
Please validate the map  @VIJAYGOKULRAJ

**Comment by VIJAYGOKULRAJ** [comment]
https://github.com/VIJAYGOKULRAJ/project-api/assets/144028547/fc6bdf51-f2a0-4132-9c86-a81b024bc35d

Thank you jegan I done my changes.
